mytuple1="Ασημίνα","Μήλο","Python"
print('Πλειάδα:',mytuple1)
print('Πλήθος:',len(mytuple1))
print('Τύπος: ',type(mytuple1))
print()
mytuple2=("Ασημίνα",)
print('Πλειάδα:',mytuple2)
print('Πλήθος:',len(mytuple2))
print('τύπος: ',type(mytuple2))
print()
mytuple3=("Ασημίνα")
#αν δεν βάλουμε κόμμα στο τέλος το δέχεται ως string και όχι ως πλειάδα
#σαν πλήθος εμφανίζει το πλήθος χαρακτήρων του string
print("συμβολοσειρά",mytuple3)
print("Πλήθος: ",len(mytuple3))
print('Τύπος:',type(mytuple3))
print()
mytuple4=tuple(("Python",6,"Γιώργος"))
print('Πλειάδα:',mytuple4)
print('Πλήθος: ',len(mytuple4))
print('Τύπος:',type(mytuple4))
print()
mytuple5=tuple(())
print('Πλειάδα: ',mytuple5)
print('Πλήθος: ',len(mytuple5))
print('Τύπος: ',type(mytuple5))
print()
